### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by aep** [apparentlymart/go-kicad#1]
license would be great

**Comment by apparentlymart** [comment]
Worth noting that this is unfinished and largely abandoned at this point, but sure, I can put a licence on it.

**Comment by apparentlymart** [comment]
MIT license added in 83fdb341b545b3da90871cd8094052632fe688e2

**Comment by aep** [comment]
Thanks!

That's fine, but always good to have as starting point :)

**Comment by apparentlymart** [comment]
It's been a while since I looked at this so I can't really say with certainty what state it's in, but I remember that there were some problems with the design of the `sexp` package that meant it could not decode certain permutations of s-expressions in one or more of the kicad formats, due to the difference of approach where kicad itself (IIRC) decodes these structures in a "pull" sort of way, switching parsing modes on the fly as it goes, whereas this `sexp` package is trying to do everything declaratively using struct tags.

It might be better to rework it to have a lower-level layer similar to the parser in the kicad code, and then try to implement the decoder on top of that in a manner similar to the `encoding/json` package's `Marshaler`/`Unmarshaler` interfaces, thus allowing the tricky stuff to be dealt with using custom code where needed.

If you have the time and motivation to actually make this work, that'd be awesome! My side-project that was gonna use this wasn't interesting enough to keep me motivated through a refactor. :confounded:

**Comment by aep** [comment]
this is really helpful info, thanks alot!

i dunno what i'm going to do yet. With eagle being dead i'm just exploring the kicad universe. Eagle had a large community with community fixes that made it bearable.

I just discovered that the smallest unit is 1mil, making it very inacurate for metrics based (almost everything) design. Do you happen to know if this is reflected in the file format? i.e. is accuracy lost in the file itself as well, or where they smart enough to use floats?
